from __future__ import annotations

from uuid import UUID

from pydantic import Field
from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, OptionalNullable, RFC3339DateTime, SdkBaseModel
from .enums.asset_class import AssetClassOrStr
from .enums.order_class import OrderClassOrStr
from .enums.order_side import OrderSideOrStr
from .enums.order_status import OrderStatusOrStr
from .enums.order_type import OrderTypeOrStr
from .enums.time_in_force import TimeInForceOrStr


class Order(SdkBaseModel):
    """The Orders API allows a user to monitor, place and cancel their orders with Alpaca.

    Each order has a unique identifier provided by the client. This client-side unique order ID will be automatically
    generated by the system if not provided by the client, and will be returned as part of the order object along with
    the rest of the fields described below. Once an order is placed, it can be queried using the client-side order ID to
    check the status.

    Updates on open orders at Alpaca will also be sent over the streaming interface, which is the recommended method of
    maintaining order state."""

    id: Optional[str] = UNSET
    """Order ID"""

    client_order_id: Optional[str] = UNSET
    """Client unique order ID"""

    created_at: Optional[RFC3339DateTime] = UNSET
    updated_at: OptionalNullable[RFC3339DateTime] = UNSET
    submitted_at: OptionalNullable[RFC3339DateTime] = UNSET
    filled_at: OptionalNullable[RFC3339DateTime] = UNSET
    expired_at: OptionalNullable[RFC3339DateTime] = UNSET
    canceled_at: OptionalNullable[RFC3339DateTime] = UNSET
    failed_at: OptionalNullable[RFC3339DateTime] = UNSET
    replaced_at: OptionalNullable[RFC3339DateTime] = UNSET
    replaced_by: OptionalNullable[UUID] = UNSET
    """The order ID that this order was replaced by"""

    replaces: OptionalNullable[UUID] = UNSET
    """The order ID that this order replaces"""

    asset_id: Optional[UUID] = UNSET
    """Asset ID"""

    symbol: str
    """Asset symbol"""

    asset_class: Optional[AssetClassOrStr] = UNSET
    """Represents what class of asset this is. Currently only supports ``us_equity`` or ``crypto``"""

    notional: str | None
    """Ordered notional amount. If entered, qty will be null. Can take up to 9 decimal points."""

    qty: str | None
    """Ordered quantity. If entered, notional will be null. Can take up to 9 decimal points."""

    filled_qty: Optional[str] = UNSET
    """Filled quantity"""

    filled_avg_price: OptionalNullable[str] = UNSET
    """Filled average price"""

    order_class: Optional[OrderClassOrStr] = UNSET
    """This will either be the empty string "", "simple", "bracket", "oco", or "oto"."""

    order_type: Optional[str] = UNSET
    """Deprecated in favour of the field "type"
    """

    type_: OrderTypeOrStr = Field(alias="type")
    """Represents the types of orders Alpaca currently supports

    - market
    - limit
    - stop
    - stop_limit
    - trailing_stop"""

    side: OrderSideOrStr
    """Represents which side this order was on:

    - buy
    - sell"""

    time_in_force: TimeInForceOrStr
    """Note: For Crypto Trading, Alpaca supports the following Time-In-Force designations: day, gtc, ioc and fok. OPG
    and CLS are not supported.

    Alpaca supports the following Time-In-Force designations:

    - day
      A day order is eligible for execution only on the day it is live. By default, the order is only valid during
        Regular Trading Hours (9:30am - 4:00pm ET). If unfilled after the closing auction, it is automatically canceled.
        If submitted after the close, it is queued and submitted the following trading day. However, if marked as
        eligible for extended hours, the order can also execute during supported extended hours.

    - gtc
      The order is good until canceled. Non-marketable GTC limit orders are subject to price adjustments to offset
        corporate actions affecting the issue. We do not currently support Do Not Reduce(DNR) orders to opt out of such
        price adjustments.

    - opg
      Use this TIF with a market/limit order type to submit “market on open” (MOO) and “limit on open” (LOO) orders.
        This order is eligible to execute only in the market opening auction. Any unfilled orders after the open will be
        cancelled. OPG orders submitted after 9:28am but before 7:00pm ET will be rejected. OPG orders submitted after
        7:00pm will be queued and routed to the following day’s opening auction. On open/on close orders are routed to
        the primary exchange. Such orders do not necessarily execute exactly at 9:30am / 4:00pm ET but execute per the
        exchange’s auction rules.

    - cls
      Use this TIF with a market/limit order type to submit “market on close” (MOC) and “limit on close” (LOC) orders.
        This order is eligible to execute only in the market closing auction. Any unfilled orders after the close will
        be cancelled. CLS orders submitted after 3:50pm but before 7:00pm ET will be rejected. CLS orders submitted
        after 7:00pm will be queued and routed to the following day’s closing auction. Only available with API v2.

    - ioc
      An Immediate Or Cancel (IOC) order requires all or part of the order to be executed immediately. Any unfilled
        portion of the order is canceled. Only available with API v2. Most market makers who receive IOC orders will
        attempt to fill the order on a principal basis only, and cancel any unfilled balance. On occasion, this can
        result in the entire order being cancelled if the market maker does not have any existing inventory of the
        security in question.

    - fok
      A Fill or Kill (FOK) order is only executed if the entire order quantity can be filled, otherwise the order is
        canceled. Only available with API v2."""

    limit_price: OptionalNullable[str] = UNSET
    """Limit price"""

    stop_price: OptionalNullable[str] = UNSET
    """Stop price"""

    status: Optional[OrderStatusOrStr] = UNSET
    """An order executed through Alpaca can experience several status changes during its lifecycle. The most common
    statuses are described in detail below:

    - new
      The order has been received by Alpaca, and routed to exchanges for execution. This is the usual initial state of
        an order.

    - partially_filled
      The order has been partially filled.

    - filled
      The order has been filled, and no further updates will occur for the order.

    - done_for_day
      The order is done executing for the day, and will not receive further updates until the next trading day.

    - canceled
      The order has been canceled, and no further updates will occur for the order. This can be either due to a cancel
        request by the user, or the order has been canceled by the exchanges due to its time-in-force.

    - expired
      The order has expired, and no further updates will occur for the order.

    - replaced
      The order was replaced by another order, or was updated due to a market event such as corporate action.

    - pending_cancel
      The order is waiting to be canceled.

    - pending_replace
      The order is waiting to be replaced by another order. The order will reject cancel request while in this state.

    Less common states are described below. Note that these states only occur on very rare occasions, and most users
    will likely never see their orders reach these states:

    - accepted
      The order has been received by Alpaca, but hasn’t yet been routed to the execution venue. This could be seen often
        out side of trading session hours.

    - pending_new
      The order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted for execution.
        This state only occurs on rare occasions.

    - accepted_for_bidding
      The order has been received by exchanges, and is evaluated for pricing. This state only occurs on rare occasions.

    - stopped
      The order has been stopped, and a trade is guaranteed for the order, usually at a stated price or better, but has
        not yet occurred. This state only occurs on rare occasions.

    - rejected
      The order has been rejected, and no further updates will occur for the order. This state occurs on rare occasions
        and may occur based on various conditions decided by the exchanges.

    - suspended
      The order has been suspended, and is not eligible for trading. This state only occurs on rare occasions.

    - calculated
      The order has been completed for the day (either filled or done for day), but remaining settlement calculations
        are still pending. This state only occurs on rare occasions.


    An order may be canceled through the API up until the point it reaches a state of either filled, canceled, or
    expired."""

    extended_hours: Optional[bool] = UNSET
    """If true, eligible for execution outside regular trading hours."""

    legs: Optional[list[Order | None]] = UNSET
    """When querying non-simple order_class orders in a nested style, an array of Order entities associated with this
    order. Otherwise, null."""

    trail_percent: Optional[str] = UNSET
    """The percent value away from the high water mark for trailing stop orders."""

    trail_price: Optional[str] = UNSET
    """The dollar value away from the high water mark for trailing stop orders."""

    hwm: Optional[str] = UNSET
    """The highest (lowest) market price seen since the trailing stop order was submitted."""


class OrderDict(TypedDict):
    id: NotRequired[str]
    client_order_id: NotRequired[str]
    created_at: NotRequired[RFC3339DateTime]
    updated_at: NotRequired[RFC3339DateTime | None]
    submitted_at: NotRequired[RFC3339DateTime | None]
    filled_at: NotRequired[RFC3339DateTime | None]
    expired_at: NotRequired[RFC3339DateTime | None]
    canceled_at: NotRequired[RFC3339DateTime | None]
    failed_at: NotRequired[RFC3339DateTime | None]
    replaced_at: NotRequired[RFC3339DateTime | None]
    replaced_by: NotRequired[UUID | None]
    replaces: NotRequired[UUID | None]
    asset_id: NotRequired[UUID]
    symbol: str
    asset_class: NotRequired[AssetClassOrStr]
    notional: str | None
    qty: str | None
    filled_qty: NotRequired[str]
    filled_avg_price: NotRequired[str | None]
    order_class: NotRequired[OrderClassOrStr]
    order_type: NotRequired[str]
    type_: OrderTypeOrStr
    side: OrderSideOrStr
    time_in_force: TimeInForceOrStr
    limit_price: NotRequired[str | None]
    stop_price: NotRequired[str | None]
    status: NotRequired[OrderStatusOrStr]
    extended_hours: NotRequired[bool]
    legs: NotRequired[list[Order | OrderDict | None]]
    trail_percent: NotRequired[str]
    trail_price: NotRequired[str]
    hwm: NotRequired[str]
