from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .order import Order, OrderDict


class PositionClosedReponse(SdkBaseModel):
    """Represents the result of asking the api to close a position."""

    symbol: str
    """Symbol name of the asset"""

    status: str
    """Http status code for the attempt to close this position"""

    body: Optional[Order] = UNSET
    """The Orders API allows a user to monitor, place and cancel their orders with Alpaca.

    Each order has a unique identifier provided by the client. This client-side unique order ID will be automatically
    generated by the system if not provided by the client, and will be returned as part of the order object along with
    the rest of the fields described below. Once an order is placed, it can be queried using the client-side order ID to
    check the status.

    Updates on open orders at Alpaca will also be sent over the streaming interface, which is the recommended method of
    maintaining order state."""


class PositionClosedReponseDict(TypedDict):
    symbol: str
    status: str
    body: NotRequired[Order | OrderDict]
